### ISSUE TITLE
Renaming a Server Role results in a you loss of the configuration Plan

### ISSUE THREAD

**Issue by pcamelio** [Inedo/inedox-inedocore#82]
Otter 2.0.8
When you rename a Server Role, the configuration plan disappears
When you rollback, the configuration plan reappears

**Comment by whatatripp** [comment]
This is an expected behavior, and we recently added a warning...

https://inedo.myjetbrains.com/youtrack/issue/OT-208

... the main issue is that renaming is particularly complicated because items are stored in raft repositories. So renaming would need to be an execution that tries to rename it in the raft, and rolls back the rename if it doesn't succeed.
